name: Deploy Staging

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages (staging-workbench.unyt.org)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: staging-workbench.unyt.org
